Add the U32 Version payload to the 0x0D VERSION messages
WebThingsIO/deconz-api pull request #17
Opened 2020-12-05 03:32 UTC by chas-iot

Part 1 (of 2) of handling the latest deconz firmware

Original code from @frederic34 in https://github.com/WebThingsIO/serial-prober-node/issues/11#issuecomment-736284238

From reading the spec at page 9 of
https://deconz.dresden-elektronik.de/raspbian/deCONZ-Serial-Protocol-en_1.14.pdf
this should already have been present since at least 2019.
Apparently the newer firmware is more strict and checks message lengths,
rejecting messages for incorrect formats.

2020-12-05 03:35 UTC, chas-iot commented
@frederic34 @dhylands @mrstegeman 
I'm not able to test this on untouched ConBee II firmware (and I'm not even sure what firmware I started with)

Partial fix for https://github.com/WebThingsIO/serial-prober-node/issues/11 - Part 2 to follow
This may also help fix https://github.com/WebThingsIO/zigbee-adapter/issues/260

2020-12-05 03:53 UTC, mrstegeman commented
I do not have a ConBee dongle to test with, so I need somebody else to test this. Perhaps @kgiori?

2020-12-05 03:57 UTC, kgiori commented
What do I have to do?

2020-12-05 03:58 UTC, kgiori commented
I am definitely having Zigbee issues in the last couple weeks. Mostly my pushbuttons. :(

2020-12-05 04:02 UTC, chas-iot commented
@kgiori, please hold off until I complete part 2 of this fix, which is in the ZigBee adapter.

I'll explain, the explanation will likely take longer than the coding and I might not get to it today (Saturday afternoon in my time-zone) - demands from $other-life.

2020-12-05 04:43 UTC, chas-iot commented
fixes https://github.com/WebThingsIO/serial-prober-node/issues/11

part 2 is in https://github.com/WebThingsIO/zigbee-adapter/pull/265

2020-12-05 09:44 UTC, chas-iot commented
@mrstegeman please review and suggest any required changes to these instructions.
@kgiori - If you are interested in helping then thank-you 🙂 

This is part 1 of 2 changes to support ConBee / RaspBee ZigBee devices with very recent firmware. The purpose of this testing that we are asking you to do is to ensure that the changes do not break anything for with devices without upgraded firmware.

Steps:
1. Backup .webthings/addons/zigbee-adapter/node_modules/deconz-api/lib/frame-builder.js
1. Extract https://github.com/chas-iot/deconz-api/blob/fix-format/lib/frame-builder.js to .webthings/addons/zigbee-adapter/node_modules/deconz-api/lib - If you are not using a Raspberry Pi, the destination installation path may be different
1. In the gateway UI, go to Settings / Add-ons / ZigBee / Configure
1. Set debug to __serialProber__ then click Apply
1. Wait 30 seconds
1. Check the Developer logs for startup errors - Please let us know the results.
1. If everything just works, please do not backout the change until Part 2 is also tested

Possible issues:
- The gateway may complain if code in a node module does not match the released version. I don't think it will complain. If it does, then just create a .git directory in .webthings/addons/zigbee-adapter/node_modules/deconz-api/lib - and if that doen't work, create a .git directory in .webthings/addons/zigbee-adapter
- The ZigBee adapter may fail to start or hang because the device does not recognise the slightly changed messages

Backout
1. remove any .git directories created above
1. remove the changed frame-builder.js and replace with the version from the backup
1. remove the debug string from the ZigBee adapter configuration

2020-12-05 20:12 UTC, mrstegeman approved these changes
Code change looks innocent enough. I'll wait to merge until it's been tested.

2020-12-06 05:24 UTC, chas-iot commented
> I am definitely having Zigbee issues in the last couple weeks. Mostly my pushbuttons. :(

Once my platform is stable again, I'll take a look to see if I can help.

2020-12-06 17:14 UTC, mrsteakhouse requested changes
Thank you for doing the hard work. I tested this with my local setup. After changing the method name and applying the test setup from the second PR everything worked again.

However i noticed that no events are emitted and i get many error messages stating `Invalid message received` or `Validation error`. That no events are emitted seems only like to affect the UI since pressing the scene buttons on my remote still have had triggered the desired rule.

2020-12-06 17:14 UTC, mrsteakhouse commented on lib/frame-builder.js
> +  builder.appendUint32LE(0);
```suggestion
  builder.appendUInt32LE(0);
```
Tested this and got an error, that the function does not exist

2020-12-06 18:36 UTC, mrstegeman commented
@mrsteakhouse were you testing these changes with an older, already working ConBee dongle?

2020-12-06 18:58 UTC, mrsteakhouse commented
At first having the old firmware i noticed an update of the addon to 0.15.3, coming from 0.15.2. After updating it stopped working. I had to flash a newer firmware to the conbee 2 and apply the steps mentioned to make it work again.

2020-12-06 19:10 UTC, mrstegeman commented
So, what we still need is someone to test 0.15.3, with these changes, on the older firmware. Correct?

2021-01-26 17:35 UTC, merged